Fixed Manifest link used in 2.13.0 docs
litmuschaos/litmus-docs pull request #209
Opened 2022-10-19 11:49 UTC by AnirudhBot

Signed-off-by: Anirudh Sharma <anirudh1304@gmail.com>

**What this PR does / why we need it**:
Fixes Manifest link used in 2.13.0 docs

**Which issue this PR fixes** 
fixes https://github.com/litmuschaos/litmus/issues/3798

**Special notes for your reviewer**:

**Checklist:**
-   [ ] Fixes #<issue number>
-   [ ] Signed the commit for DCO to be passed
-   [ ] Labelled this PR & related issue with `documentation` tag

2022-10-20 04:48 UTC, neelanjan00 requested changes

2022-10-20 04:48 UTC, neelanjan00 commented on website/versioned_docs/version-2.13.0/user-guides/uninstall-litmus.md
>    > To delete any specific version of the ChaosCenter, replace the above command with the below command. `kubectl delete -f https://raw.githubusercontent.com/litmuschaos/litmus/<VERSION>/mkdocs/docs/
```suggestion
  > To delete any specific version of the ChaosCenter, replace the above command with the below command. `kubectl delete -f https://raw.githubusercontent.com/litmuschaos/litmus/<VERSION>/mkdocs/docs/<VERSION>/litmus-<VERSION>.yaml`
```

2022-10-20 04:48 UTC, neelanjan00 commented
Thanks for the PR @AnirudhBot !

2022-10-20 11:29 UTC, gdsoumya approved these changes

2022-10-20 11:30 UTC, gdsoumya commented
Thanks for the fix @AnirudhBot 🚀

2022-10-20 11:35 UTC, neelanjan00 commented
@AnirudhBot, the typo in `<VERSION>` is there in the previous versions of the doc as well. Can you make the changes in all of them?

2022-10-27 22:29 UTC, ksatchit approved these changes
LGTM

2022-10-30 09:34 UTC, neelanjan00 approved these changes
LGTM

2022-10-30 09:35 UTC, merged