Update TOC and Overview for Consistency
litmuschaos/litmus-docs pull request #313
Opened 2024-12-10 10:12 UTC by andoriyaprashant

**What this PR does / why we need it**:

This pull request addresses the issue of inconsistent section titles and order between the Table of Contents (TOC) and the Overview pages in both the "Concepts" and "User Guides" sections.

**Concepts**

- User Guides Overview: Reordered sections to match the User Guide TOC order.
- Concepts Overview: Reordered sections to match the Concepts TOC order.

**Additional Updates:**
- Added concepts/visualize-experiment file in sidebars.js 

**Which issue this PR fixes** #300 

**Checklist:**
-   [X] Fixes #300 
-   [X] Signed the commit for DCO to be passed

2024-12-17 10:17 UTC, namkyu1999 requested changes
And could you also make consistent capitalization? For example, "Chaos experiment" is sentence-style capitalization; "Chaos Experiment" is title capitalization.

ex.
Chaos experiment -> Chaos Experiment

2024-12-17 10:17 UTC, namkyu1999 commented on website/docs/concepts/overview.md
> +### [Probes](probes.md)
```suggestion
### [Resilience Probes](probes.md)
```

2024-12-17 10:17 UTC, namkyu1999 commented on website/docs/user-guides/overview.md
> +### [Event Triggered Chaos using GitOps](gitops-configuration.md)
```suggestion
### [Configuring GitOps](gitops-configuration.md)
```

2024-12-17 10:17 UTC, namkyu1999 commented on website/versioned_docs/version-3.12.0/concepts/overview.md
> +### [Probes](probes.md)
same

2024-12-17 10:17 UTC, namkyu1999 commented on website/versioned_docs/version-3.12.0/user-guides/overview.md
> +### [Event Triggered Chaos using GitOps](gitops-configuration.md)
same

2024-12-17 16:14 UTC, andoriyaprashant commented
Done @namkyu1999

2024-12-18 04:59 UTC, namkyu1999 requested changes
Could you apply title capitalization to the text here?

<img width="302" alt="Screenshot 2024-12-18 at 1 52 52 PM" src="https://github.com/user-attachments/assets/c0c5e495-1da0-458e-aaea-f4ca8f329968" />

Chaos infrastructure -> Chaos Infrastructure
ChaosHub
Chaos experiment -> Chaos Experiment
Resilience Probes
User management -> User Management 
Projects
Teaming
GitOps
Authentication in ChaosCenter
Visualize chaos experiment -> Visualize Chaos Experiment

2024-12-18 04:59 UTC, namkyu1999 commented on website/versioned_docs/version-3.12.0/concepts/overview.md
> +### [Visualize chaos experiment](visualize-experiment.md)
```suggestion
### [Visualize Chaos Experiment](visualize-experiment.md)
```

2024-12-18 04:59 UTC, namkyu1999 commented on website/docs/concepts/overview.md
> +### [Visualize chaos experiment](visualize-experiment.md)
```suggestion
### [Visualize Chaos Experiment](visualize-experiment.md)
```

2024-12-18 05:04 UTC, andoriyaprashant commented
> Could you apply title capitalization to the text here?
> 
> 
> 
> <img width="302" alt="Screenshot 2024-12-18 at 1 52 52 PM" src="https://github.com/user-attachments/assets/c0c5e495-1da0-458e-aaea-f4ca8f329968" />
> 
> 
> 
> Chaos infrastructure -> Chaos Infrastructure
> 
> ChaosHub
> 
> Chaos experiment -> Chaos Experiment
> 
> Resilience Probes
> 
> User management -> User Management 
> 
> Projects
> 
> Teaming
> 
> GitOps
> 
> Authentication in ChaosCenter
> 
> Visualize chaos experiment -> Visualize Chaos Experiment

Oh, maybe I missed it. I'll change it right away

2024-12-19 09:26 UTC, namkyu1999 approved these changes
LGTM 🚀

2025-01-15 06:20 UTC, Saranya-jena approved these changes

2025-01-15 06:21 UTC, merged