Combined Community and More Resources pages.
litmuschaos/litmus-docs pull request #314
Opened 2024-12-18 23:01 UTC by dwelsch-esi

**What this PR does / why we need it**: 
Removes a redundant page. Makes finding community and information resources more friendly.

**Which issue this PR fixes** 
fixes #309

**Special notes for your reviewer**:
This is one of the CNCF doc issues with the techdoc-analysis label.

**Checklist:**
-   [ x] Fixes #309
-   [ x] Signed the commit for DCO to be passed
-   [ ] Labelled this PR & related issue with `documentation` tag

2024-12-19 09:39 UTC, namkyu1999 requested changes
I have one request. rest looks good to me 👍

2024-12-19 09:39 UTC, namkyu1999 commented on website/docs/introduction/community.md
> +### Attend our community meetings
Could you add more content about community and contributor meetings based on this [information](https://github.com/litmuschaos/litmus?tab=readme-ov-file#community-meetings)?

2024-12-19 09:39 UTC, namkyu1999 commented on website/versioned_docs/version-3.12.0/introduction/community.md
> +### Attend our community meetings
same

2024-12-20 06:24 UTC, namkyu1999 approved these changes

2025-01-15 06:17 UTC, Saranya-jena approved these changes

2025-01-15 06:17 UTC, merged