Updated the docs for LitmusPortal Installation with Ingress.
litmuschaos/litmus-docs pull request #35
Opened 2021-04-21 20:02 UTC by Jonsy13

Signed-off-by: Jonsy13 <vedant.shrotria@chaosnative.com>

**What this PR does / why we need it**:

**This PR will update the docs for LitmusPortal Installation with Ingress.**
Validation on EKS - ✔️ 
Validation on GKE - 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Checklist:**
-   [ ] Fixes #<issue number>
-   [X] Signed the commit for DCO to be passed
-   [X] Labelled this PR & related issue with `documentation` tag

2021-04-21 20:03 UTC, Jonsy13 commented
Do not merge, Validation on GKE yet to be done.

2021-04-22 12:48 UTC, rajdas98 requested changes

2021-04-22 12:48 UTC, rajdas98 commented on website/docs/litmus-installation-with-ingress.md
> +  type: LoadBalancer
Can we use CLusterIP? Because most of the on-prem cluster don't have LoadBalancer svc type

2021-04-30 19:52 UTC, rajdas98 approved these changes

2021-04-30 20:03 UTC, merged