Added Image Registry and ChaosHub docs
litmuschaos/litmus-docs pull request #79
Opened 2021-08-11 07:18 UTC by amityt

Signed-off-by: Amit Kumar Das <amit@chaosnative.com>

**What this PR does / why we need it**:
This PR adds:
- ChaosHub docs
- Image Registry docs

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Checklist:**
-   [ ] Fixes #<issue number>
-   [ ] Signed the commit for DCO to be passed
-   [ ] Labelled this PR & related issue with `documentation` tag

2021-08-11 07:30 UTC, vanshBhatia-A4k9 commented on website/docs/concepts/chaoshub.md
> +The following should be required before creating a Chaos Workflow:
```suggestion
The following are the prerequisites for creating a Chaos Workflow:
```

`should` indicates a possibility.. but it is in fact a mandate in this case..

2021-08-11 07:32 UTC, vanshBhatia-A4k9 approved these changes
Left a suggestion, PTAL. Rest is great :rocket:

2021-08-11 07:34 UTC, Saranya-jena commented on website/docs/concepts/chaoshub.md
> +ChaosHub allows a user to orchestrate workflows from the Public **[ChaosHub](http://hub.litmuschaos.io/)** or an alternate source for the Experiments (basically, a **[fork](https://github.com/litmusc
We should use the second person to address, as this convention is used everywhere. You can write - `ChaosHub allows a user` -> `ChaosHub allows a you`

2021-08-11 07:34 UTC, Saranya-jena commented on website/docs/concepts/chaoshub.md
> +The following should be required before creating a Chaos Workflow:
following should -> following are

2021-08-11 07:34 UTC, Saranya-jena commented on website/docs/concepts/chaoshub.md
> +With ChaosHub, a user can construct chaos workflows by selecting, tuning and sequencing different experiments together from their connected ChaosHubs.
user -> you

2021-08-11 07:34 UTC, Saranya-jena commented on website/docs/concepts/chaoshub.md
> +User can make changes in their forked repositories and sync it with the Portal to get the latest changes from the fork.
Same here

2021-08-11 07:34 UTC, Saranya-jena commented on website/docs/user-guides/image-registry.md
> +To updated the Chaos Workflow Image Registry, user can go to Settings in ChaosCenter. In settings, there will be tab named Image Registry. On clicking the Image Regitry tab, user can see that the def
Regitry -> Registry

2021-08-11 07:40 UTC, amityt commented
Have made the requested changes! Thanks for the review @Saranya-jena @vanshBhatia-A4k9

2021-08-11 07:42 UTC, Saranya-jena approved these changes
Awesome thanks! 🚀

2021-08-11 09:12 UTC, S-ayanide requested changes

2021-08-11 09:12 UTC, S-ayanide commented on website/docs/user-guides/image-registry.md
> +
Can you please add a `Before you begin` section where the associated concepts that are required as a pre-requisite will be referenced!

2021-08-11 09:12 UTC, S-ayanide commented on website/docs/user-guides/image-registry.md
> +
Can you please add some associated `Learn More` links!

2021-08-11 11:41 UTC, S-ayanide approved these changes

2021-08-12 04:26 UTC, Jonsy13 approved these changes

2021-08-12 05:04 UTC, arkajyotiMukherjee requested changes

2021-08-12 05:04 UTC, arkajyotiMukherjee commented on website/docs/concepts/chaoshub.md
> +## Introduction
Intro may not have a heading called intro...you can just start with the intro paragraph

2021-08-12 05:04 UTC, arkajyotiMukherjee commented on website/docs/user-guides/image-registry.md
> +## Image Registry
This heading might not be required

2021-08-12 05:04 UTC, arkajyotiMukherjee commented on website/docs/user-guides/image-registry.md
> +## Image Registry
This heading might not be required

2021-08-12 05:21 UTC, arkajyotiMukherjee approved these changes

2021-08-12 05:21 UTC, merged